#Travis CI runner file
sudo: required
services:
  - docker

before_install:
  - docker build -t rmathew2013/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rmathew2013/docker-react npm run test
